### ISSUE TITLE
No further information from Vigor 165 than via included SNMP check --> Crash Report

### ISSUE THREAD

**Issue by razorworks** [f-zappa/check_mk_adsl_line#2]
Hi and thanks für the additional information about the modem state via Check_MK.  
I installed version 0.7 on 1.6.0.p16, but I get a "Crash Report":  
* Exception: TypeError (argument of type 'NoneType' is not iterable)
* Traceback
```
  File "/omd/sites/heimat/lib/python/cmk_base/checking.py", line 320, in execute_check
    raw_result = check_function(item, determine_check_params(params), section_content)
  File "/omd/sites/heimat/local/share/check_mk/checks/adsl_line", line 40, in check_adsl_line
    if 'downstream_params' in params:
```
* Local Variables
```
{'info': [[u'4',
           u'2',
           u'2',
           u'.0.0',
           u'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00',
           u'DRAYTEK\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00',
           u'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00',
           u'6',
           u'13',
           u'SHOWTIME\x00\x00\x00\x00\x00\x00\x00\x00\x00',
           u'-1',
           u'293330780',
           u'285473000',
           u'46717000']],
 'item': u'4',
 'params': None}
```
* Crash Type: check
* Time: 2022-05-29 15:12:49
* Operating System: bionic
* Check_MK Version: 1.6.0p16
* Edition: cee
* Core: cmc
* Python Version: 2.7.17 (default, Aug 19 2020, 06:42:08) [GCC 8.4.0]
* Python Module Paths
```
/opt/omd/versions/1.6.0p16.cee/bin
/omd/sites/heimat/local/lib/python
/omd/sites/heimat/lib/python/_pdbpp_path_hack
/omd/sites/heimat/lib/python27.zip
/omd/sites/heimat/lib/python2.7
/omd/sites/heimat/lib/python2.7/plat-linux2
/omd/sites/heimat/lib/python2.7/lib-tk
/omd/sites/heimat/lib/python2.7/lib-old
/omd/sites/heimat/lib/python2.7/lib-dynload
/omd/sites/heimat/lib/python2.7/site-packages
/omd/sites/heimat/lib/python
```

Please let me know if you need more information to fix.  
Shall I update the site to 2.x and retry with version 1.1 again?  

Best regards,  
Razorworks

**Comment by f-zappa** [comment]
Hi, is this still relevant or are you on checkmk 2.x now? I hope it works there, just made a new fix that addresses some changes in checkmk 2.1 - please find the new version in the repo.
Regards, Uli "f-zappa"
