### ISSUE TITLE
Missing data after updating fw to 4.2.4

### ISSUE THREAD

**Issue by f-zappa** [f-zappa/check_mk_adsl_line#4]
Upstream and downstream rate are not monitored after latest firmware update. Need to correct this.

**Comment by f-zappa** [comment]
Draytek changed the returned SNMP values in Firmware 2.4.2.
In version 1.3 of the check, upstream rate is now in another SNMP data field. Downstream rate unfortunately is not within SNMP data anymore. Maybe one day I write a new check which works via telnet.

**Comment by donald2612** [comment]
Well, in my case of Vigor 165, downstream rate is showing (1.3.6.1.2.1.10.251.1.2.2.1.2.4 xdsl2ChStatusActDataRate
), but upstream rate is nowhere to be found in SNMP. You can find several people on the internet having the same sort of problems with Draytek newer firmware releases... That annoys everyone....
