### ISSUE TITLE
exchange has old version 0.7 incompatible with cmk 2.x

### ISSUE THREAD

**Issue by azrdev** [f-zappa/check_mk_adsl_line#5]
https://exchange.checkmk.com/p/adsl-line has only the one version 0.7 of the plugin, which apparently is not compatible with cmk >= 2.0 -- I had to look for quite some time for the error here until I noticed I'm using an outdated version.

Would you mind updating the exchange? Of if not, taking down the ancient version there?

**Comment by f-zappa** [comment]
Hi,
I'd like to .. but it seems I don't even have a real account there. No 
idea how I did the initial upload. Opened a thread in the forums now, 
maybe check_mk staff can help.
Regards, Uli

Am 22.12.2022 08:52, schrieb azrdev:

**Comment by f-zappa** [comment]
Yeah, check_mk people linked my package to my account so I could now upload the recent version there. Not visible now though, still needs to pass the review process.

**Comment by f-zappa** [comment]
updated this some months ago ;)
