### ISSUE TITLE
GUI rule can only overwrite upstream_rate parameter

### ISSUE THREAD

**Issue by azrdev** [f-zappa/check_mk_adsl_line#6]
I navigate the GUI to  Setup > Services > Service monitoring rules > Metrics of ADSL line   and create a "New rule: Metrics of ADSL line". In the "Value" section, this allows me to set "Upstream Rate", but not the other parameters (like SNR margin).

This is Checkmk Raw Edition 2.1.0p18 and adsl_line 1.3

**Comment by donald2612** [comment]
That is true. If I recall correctly in newer CheckMK-versions python3 now is used only and changed the way how you could combine integer + string-variables. 
![image](https://github.com/f-zappa/check_mk_adsl_line/assets/57543527/8a20b46e-ec1b-4924-83a8-f86e35176514)
The plugin simply crashes when parsing the upstream-section.
Plugin 1.4 from CMK-exchange on Checkmk Enterprise Edition 2.1.0p28

**Comment by donald2612** [comment]
Could you please review your recent changes? I've changed the code, restarted the omd-service and the error is still popping up.
Thank you!

**Comment by bernhardschmidt** [comment]
It works for me. However, there seems to be some kind of caching involved, I could not get it to work changing the local file either, I had to build a new package with the modified files in the filesystem with mkp pack and then remove/install it again.

![grafik](https://github.com/f-zappa/check_mk_adsl_line/assets/772230/cb16efba-3634-4aae-a829-8357a89e08ad)

**Comment by donald2612** [comment]
Oh, yes you are right. Once fully corrected version was repackaged and all old assets of the old extension were removed, it finally works. And firmware 4.2.5 finally fixes the missing upload- SNMP-OID.

@Bernhard: There is still one missing 'hash' in line two of your corrected script!!

Thanks for you contribution!
